-- MySQL Script generated by MySQL Workbench
-- Mon Dec 25 10:37:24 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Ser_Humano
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Ser_Humano` ;

-- -----------------------------------------------------
-- Schema Ser_Humano
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Ser_Humano` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `Ser_Humano` ;

-- -----------------------------------------------------
-- Table `Ser_Humano`.`departamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ser_Humano`.`departamentos` ;

CREATE TABLE IF NOT EXISTS `Ser_Humano`.`departamentos` (
  `num_departamento` VARCHAR(3) NOT NULL,
  `departamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`num_departamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ser_Humano`.`municipios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ser_Humano`.`municipios` ;

CREATE TABLE IF NOT EXISTS `Ser_Humano`.`municipios` (
  `num_municipio` VARCHAR(3) NOT NULL,
  `num_departamento` VARCHAR(3) NOT NULL,
  `municipio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`num_municipio`, `num_departamento`),
  INDEX `fk_municipio_departamento1_idx` (`num_departamento` ASC),
  CONSTRAINT `fk_municipio_departamento1`
    FOREIGN KEY (`num_departamento`)
    REFERENCES `Ser_Humano`.`departamentos` (`num_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ser_Humano`.`tipos_documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ser_Humano`.`tipos_documento` ;

CREATE TABLE IF NOT EXISTS `Ser_Humano`.`tipos_documento` (
  `tipo_doc_id` VARCHAR(3) NOT NULL,
  `tipo_documento` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`tipo_doc_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ser_Humano`.`tutores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ser_Humano`.`tutores` ;

CREATE TABLE IF NOT EXISTS `Ser_Humano`.`tutores` (
  `tutor_id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(80) NOT NULL,
  `apellido1` VARCHAR(45) NOT NULL,
  `apellido2` VARCHAR(45) NULL,
  `tipo_doc` VARCHAR(3) NOT NULL,
  `numero` VARCHAR(20) NOT NULL,
  `sexo` VARCHAR(10) NOT NULL,
  `nacionalidad` VARCHAR(45) NOT NULL,
  `lbrta_mil_clase` VARCHAR(45) NULL,
  `num_lbrta_mil` VARCHAR(20) NULL,
  `DM` VARCHAR(45) NULL,
  `fecha_nacim` DATE NOT NULL,
  `pais_nacim` VARCHAR(45) NOT NULL,
  `depto_nacim` VARCHAR(3) NOT NULL,
  `mun_nacim` VARCHAR(3) NOT NULL,
  `direccion_corresp` VARCHAR(45) NOT NULL,
  `pais_corresp` VARCHAR(45) NOT NULL,
  `depto_corresp` VARCHAR(3) NOT NULL,
  `mun_corresp` VARCHAR(3) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `ultm_grd_aprob` VARCHAR(45) NOT NULL,
  `titulo_obtenido` VARCHAR(90) NULL,
  `fecha_grado` DATE NOT NULL,
  `fecha_dilig` DATE NOT NULL,
  `ciudad_dilig` VARCHAR(50) NOT NULL,
  `observaciones` VARCHAR(255) NULL,
  PRIMARY KEY (`tutor_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_lg_nac_mun_idx` (`mun_nacim` ASC, `depto_nacim` ASC),
  INDEX `fk_datos_personales_2_idx` (`depto_corresp` ASC, `mun_corresp` ASC),
  INDEX `fk_datos_personales_tipo_documento_idx` (`tipo_doc` ASC),
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC),
  CONSTRAINT `fk_tutor_depto_nacim`
    FOREIGN KEY (`mun_nacim` , `depto_nacim`)
    REFERENCES `Ser_Humano`.`municipios` (`num_municipio` , `num_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tutor_2`
    FOREIGN KEY (`depto_corresp` , `mun_corresp`)
    REFERENCES `Ser_Humano`.`municipios` (`num_municipio` , `num_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tutor_tipo_documento`
    FOREIGN KEY (`tipo_doc`)
    REFERENCES `Ser_Humano`.`tipos_documento` (`tipo_doc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ser_Humano`.`modalidad_academica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ser_Humano`.`modalidad_academica` ;

CREATE TABLE IF NOT EXISTS `Ser_Humano`.`modalidad_academica` (
  `modalidad_id` INT NOT NULL,
  `modalidad` VARCHAR(3) NOT NULL COMMENT 'Tecnica(T) - Tecnologia (TC) - Tecnologia Especializada(TE) - Universitaria(UN) - Especialización(ES) - Maestria o Magister(MG) - Doctorado o PHD(DOC)',
  PRIMARY KEY (`modalidad_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ser_Humano`.`educacion_superior`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ser_Humano`.`educacion_superior` ;

CREATE TABLE IF NOT EXISTS `Ser_Humano`.`educacion_superior` (
  `educacion_superior_id` INT NOT NULL AUTO_INCREMENT,
  `modalidad_academica_id` INT NOT NULL,
  `tutor` INT NOT NULL,
  `numero_semest_aprob` VARCHAR(2) NOT NULL,
  `graduado` VARCHAR(2) NOT NULL,
  `estudio_titulo_obte` VARCHAR(45) NULL,
  `fecha_terminacion` DATE NULL,
  `num_tarjeta_prof` VARCHAR(20) NULL,
  PRIMARY KEY (`educacion_superior_id`),
  INDEX `fk_educacion_superior_modalidad_academica_idx` (`modalidad_academica_id` ASC),
  INDEX `fk_educacion_superior_datos_personales1_idx` (`tutor` ASC),
  UNIQUE INDEX `num_tarjeta_prof_UNIQUE` (`num_tarjeta_prof` ASC),
  CONSTRAINT `fk_educacion_superior_modalidad_academica`
    FOREIGN KEY (`modalidad_academica_id`)
    REFERENCES `Ser_Humano`.`modalidad_academica` (`modalidad_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_educacion_superior_tutor`
    FOREIGN KEY (`tutor`)
    REFERENCES `Ser_Humano`.`tutores` (`tutor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ser_Humano`.`experiencia_laboral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ser_Humano`.`experiencia_laboral` ;

CREATE TABLE IF NOT EXISTS `Ser_Humano`.`experiencia_laboral` (
  `experiencia_id` INT NOT NULL AUTO_INCREMENT,
  `tutor` INT NOT NULL,
  `empresa_entidad` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(10) NULL,
  `pais` VARCHAR(45) NOT NULL,
  `departamento` VARCHAR(3) NOT NULL,
  `municipio` VARCHAR(3) NOT NULL,
  `correo_entidad` VARCHAR(45) NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `fecha_retiro` DATE NOT NULL,
  `cargo_contratado` VARCHAR(45) NOT NULL,
  `dependencia` VARCHAR(45) NULL,
  `direccion` VARCHAR(80) NOT NULL,
  `estado_contrato` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`experiencia_id`),
  INDEX `fk_experiencia_laboral_municipio_idx` (`departamento` ASC, `municipio` ASC),
  INDEX `fk_experiencia_laboral_tutor_idx` (`tutor` ASC),
  CONSTRAINT `fk_experiencia_laboral_tutor`
    FOREIGN KEY (`tutor`)
    REFERENCES `Ser_Humano`.`tutores` (`tutor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_experiencia_laboral_municipio`
    FOREIGN KEY (`departamento` , `municipio`)
    REFERENCES `Ser_Humano`.`municipios` (`num_departamento` , `num_municipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ser_Humano`.`anexo_hoja_vida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ser_Humano`.`anexo_hoja_vida` ;

CREATE TABLE IF NOT EXISTS `Ser_Humano`.`anexo_hoja_vida` (
  `anexo_id` INT NOT NULL AUTO_INCREMENT,
  `tutor` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `uibicacion` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `extension` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`anexo_id`),
  INDEX `fk_anexos_hoja_vida_datos_personales1_idx` (`tutor` ASC),
  CONSTRAINT `fk_anexos_hoja_vida_tutor`
    FOREIGN KEY (`tutor`)
    REFERENCES `Ser_Humano`.`tutores` (`tutor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ser_Humano`.`etnia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ser_Humano`.`etnia` ;

CREATE TABLE IF NOT EXISTS `Ser_Humano`.`etnia` (
  `etnia_id` VARCHAR(5) NOT NULL,
  `etnia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`etnia_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ser_Humano`.`discapacidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ser_Humano`.`discapacidades` ;

CREATE TABLE IF NOT EXISTS `Ser_Humano`.`discapacidades` (
  `discapacidad_id` VARCHAR(3) NOT NULL,
  `discapacidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`discapacidad_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ser_Humano`.`capacidades_excepcionales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ser_Humano`.`capacidades_excepcionales` ;

CREATE TABLE IF NOT EXISTS `Ser_Humano`.`capacidades_excepcionales` (
  `cad_excep_id` VARCHAR(3) NOT NULL,
  `capacidad_excepcional` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cad_excep_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ser_Humano`.`alumnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ser_Humano`.`alumnos` ;

CREATE TABLE IF NOT EXISTS `Ser_Humano`.`alumnos` (
  `alumno_id` INT NOT NULL AUTO_INCREMENT,
  `tipo_documento` VARCHAR(3) NOT NULL,
  `numero_documento` VARCHAR(30) NOT NULL,
  `lugar_exp_mun` VARCHAR(3) NOT NULL,
  `lugar_exp_depto` VARCHAR(3) NOT NULL,
  `apellido_1` VARCHAR(45) NOT NULL,
  `apellido_2` VARCHAR(45) NULL,
  `nombre_1` VARCHAR(45) NOT NULL,
  `nombre_2` VARCHAR(45) NULL,
  `fecha_nac` DATE NOT NULL,
  `lugar_nac_mun` VARCHAR(3) NOT NULL,
  `lugar_nac_depto` VARCHAR(3) NOT NULL,
  `genero` VARCHAR(1) NOT NULL,
  `discapacidad` VARCHAR(3) NOT NULL,
  `cap_excepcionales` VARCHAR(3) NOT NULL,
  `anexo_documento` VARCHAR(255) NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`alumno_id`),
  INDEX `fk_alumno_tipo_documento1_idx` (`tipo_documento` ASC),
  INDEX `fk_alumno_tipo_discapacidad1_idx` (`discapacidad` ASC),
  INDEX `fk_alumno_capacidad_execpcional1_idx` (`cap_excepcionales` ASC),
  INDEX `fk_alumno_municipio1_idx` (`lugar_exp_mun` ASC, `lugar_exp_depto` ASC),
  INDEX `fk_alumno_municipio2_idx` (`lugar_nac_mun` ASC, `lugar_nac_depto` ASC),
  UNIQUE INDEX `uk_alumno_documento` (`tipo_documento` ASC, `numero_documento` ASC),
  CONSTRAINT `fk_alumno_tipo_documento1`
    FOREIGN KEY (`tipo_documento`)
    REFERENCES `Ser_Humano`.`tipos_documento` (`tipo_doc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumno_tipo_discapacidad1`
    FOREIGN KEY (`discapacidad`)
    REFERENCES `Ser_Humano`.`discapacidades` (`discapacidad_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumno_capacidad_execpcional1`
    FOREIGN KEY (`cap_excepcionales`)
    REFERENCES `Ser_Humano`.`capacidades_excepcionales` (`cad_excep_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumno_municipio1`
    FOREIGN KEY (`lugar_exp_mun` , `lugar_exp_depto`)
    REFERENCES `Ser_Humano`.`municipios` (`num_municipio` , `num_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumno_municipio2`
    FOREIGN KEY (`lugar_nac_mun` , `lugar_nac_depto`)
    REFERENCES `Ser_Humano`.`municipios` (`num_municipio` , `num_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ser_Humano`.`instituciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ser_Humano`.`instituciones` ;

CREATE TABLE IF NOT EXISTS `Ser_Humano`.`instituciones` (
  `institucion_id` INT NOT NULL AUTO_INCREMENT,
  `cod_mun_dist` VARCHAR(3) NOT NULL,
  `cod_depto_dist` VARCHAR(3) NOT NULL,
  `cod_dane_ie` VARCHAR(12) NOT NULL,
  `cod_dane_antiguo` VARCHAR(12) NOT NULL,
  `consecutivo_sede` VARCHAR(14) NOT NULL,
  `establecimiento_educativo` VARCHAR(45) NOT NULL,
  `logo` VARCHAR(255) NULL,
  `nombre_rector` VARCHAR(45) NOT NULL,
  `cedula_rector` VARCHAR(45) NOT NULL,
  `correo_rector` VARCHAR(45) NULL,
  PRIMARY KEY (`institucion_id`),
  INDEX `fk_institucion_municipio1_idx` (`cod_mun_dist` ASC, `cod_depto_dist` ASC),
  CONSTRAINT `fk_institucion_municipio1`
    FOREIGN KEY (`cod_mun_dist` , `cod_depto_dist`)
    REFERENCES `Ser_Humano`.`municipios` (`num_municipio` , `num_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ser_Humano`.`grados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ser_Humano`.`grados` ;

CREATE TABLE IF NOT EXISTS `Ser_Humano`.`grados` (
  `clei` VARCHAR(2) NOT NULL,
  `grado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`clei`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ser_Humano`.`pvc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ser_Humano`.`pvc` ;

CREATE TABLE IF NOT EXISTS `Ser_Humano`.`pvc` (
  `pvc_id` VARCHAR(2) NOT NULL,
  `pvc` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pvc_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ser_Humano`.`resguardos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ser_Humano`.`resguardos` ;

CREATE TABLE IF NOT EXISTS `Ser_Humano`.`resguardos` (
  `resguardo_id` VARCHAR(5) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`resguardo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ser_Humano`.`matricula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ser_Humano`.`matricula` ;

CREATE TABLE IF NOT EXISTS `Ser_Humano`.`matricula` (
  `matricula_id` INT NOT NULL AUTO_INCREMENT,
  `alumno_id` INT NOT NULL,
  `institucion_id` INT NOT NULL,
  `tutor_id` INT NOT NULL,
  `jornada` VARCHAR(3) NOT NULL,
  `caracter` VARCHAR(3) NOT NULL,
  `especialidad` VARCHAR(2) NOT NULL,
  `grado` VARCHAR(2) NOT NULL,
  `grupo_curso` VARCHAR(5) NULL,
  `metodologia` VARCHAR(3) NOT NULL,
  `subsidiado` VARCHAR(1) NOT NULL,
  `repitente` VARCHAR(1) NOT NULL,
  `nie` VARCHAR(1) NOT NULL,
  `saaa` VARCHAR(1) NOT NULL,
  `cafaa` VARCHAR(1) NOT NULL,
  `fuente_recursos` VARCHAR(1) NOT NULL,
  `zra` VARCHAR(1) NOT NULL,
  `amcf` VARCHAR(1) NOT NULL,
  `bvfp` VARCHAR(1) NOT NULL,
  `bhdmcf` VARCHAR(1) NOT NULL,
  `bhn` VARCHAR(1) NOT NULL,
  `pvc` VARCHAR(2) NOT NULL,
  `ume` VARCHAR(3) NULL,
  `ude` VARCHAR(3) NULL,
  `sector_privado` VARCHAR(1) NOT NULL,
  `pom` VARCHAR(1) NOT NULL,
  `etnia` VARCHAR(5) NULL,
  `resguardo` VARCHAR(5) NULL,
  `ibo` VARCHAR(10) NOT NULL,
  `sisben` VARCHAR(3) NOT NULL,
  `direccion_residencia` VARCHAR(80) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `lrm` VARCHAR(3) NULL,
  `lrd` VARCHAR(3) NULL,
  `estrato` VARCHAR(1) NOT NULL,
  `anos_cumplido` VARCHAR(3) NOT NULL,
  `fecha_matricula` DATE NOT NULL,
  `ano_reporte` VARCHAR(4) NOT NULL,
  `anexo_certif_ante` VARCHAR(255) NULL,
  PRIMARY KEY (`matricula_id`),
  INDEX `fk_matricula_institucion1_idx` (`institucion_id` ASC),
  INDEX `fk_matricula_pvc1_idx` (`pvc` ASC),
  INDEX `fk_matricula_municipio1_idx` (`ume` ASC, `ude` ASC),
  INDEX `fk_matricula_municipio2_idx` (`lrm` ASC, `lrd` ASC),
  INDEX `fk_matricula_grado1_idx` (`grado` ASC),
  INDEX `fk_matricula_resguardo_idx` (`resguardo` ASC),
  INDEX `fk_matricula_etnia_idx` (`etnia` ASC),
  INDEX `fk_matricula_tutor_id_idx` (`tutor_id` ASC),
  UNIQUE INDEX `uk_matricula_alumno_ano` (`alumno_id` ASC, `ano_reporte` ASC),
  CONSTRAINT `fk_matricula_alumno1`
    FOREIGN KEY (`alumno_id`)
    REFERENCES `Ser_Humano`.`alumnos` (`alumno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_institucion1`
    FOREIGN KEY (`institucion_id`)
    REFERENCES `Ser_Humano`.`instituciones` (`institucion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_pvc1`
    FOREIGN KEY (`pvc`)
    REFERENCES `Ser_Humano`.`pvc` (`pvc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_municipio1`
    FOREIGN KEY (`ume` , `ude`)
    REFERENCES `Ser_Humano`.`municipios` (`num_municipio` , `num_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_municipio2`
    FOREIGN KEY (`lrm` , `lrd`)
    REFERENCES `Ser_Humano`.`municipios` (`num_municipio` , `num_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_grado1`
    FOREIGN KEY (`grado`)
    REFERENCES `Ser_Humano`.`grados` (`clei`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_resguardo`
    FOREIGN KEY (`resguardo`)
    REFERENCES `Ser_Humano`.`resguardos` (`resguardo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_etnia`
    FOREIGN KEY (`etnia`)
    REFERENCES `Ser_Humano`.`etnia` (`etnia_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_tutor_id`
    FOREIGN KEY (`tutor_id`)
    REFERENCES `Ser_Humano`.`tutores` (`tutor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ser_Humano`.`cuentas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ser_Humano`.`cuentas` ;

CREATE TABLE IF NOT EXISTS `Ser_Humano`.`cuentas` (
  `cuenta_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `foto_perfil` VARCHAR(255) NULL,
  `tipo_cuenta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cuenta_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ser_Humano`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ser_Humano`.`roles` ;

CREATE TABLE IF NOT EXISTS `Ser_Humano`.`roles` (
  `rol_id` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`rol_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ser_Humano`.`modulos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ser_Humano`.`modulos` ;

CREATE TABLE IF NOT EXISTS `Ser_Humano`.`modulos` (
  `modulo_id` INT NOT NULL AUTO_INCREMENT,
  `modulo` VARCHAR(45) NOT NULL,
  `ar` TINYINT NOT NULL,
  PRIMARY KEY (`modulo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ser_Humano`.`rol_modulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ser_Humano`.`rol_modulo` ;

CREATE TABLE IF NOT EXISTS `Ser_Humano`.`rol_modulo` (
  `rol_id` INT NOT NULL,
  `rol_modulo` INT NOT NULL,
  PRIMARY KEY (`rol_id`, `rol_modulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ser_Humano`.`cuentas_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ser_Humano`.`cuentas_roles` ;

CREATE TABLE IF NOT EXISTS `Ser_Humano`.`cuentas_roles` (
  `cuenta_id` INT NOT NULL,
  `rol_id` INT NOT NULL,
  PRIMARY KEY (`cuenta_id`, `rol_id`),
  INDEX `fk_usuarios_has_roles_roles1_idx` (`rol_id` ASC),
  INDEX `fk_usuarios_has_roles_usuarios1_idx` (`cuenta_id` ASC),
  CONSTRAINT `fk_usuarios_has_roles_usuarios1`
    FOREIGN KEY (`cuenta_id`)
    REFERENCES `Ser_Humano`.`cuentas` (`cuenta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_roles_roles1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `Ser_Humano`.`roles` (`rol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ser_Humano`.`roles_modulos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ser_Humano`.`roles_modulos` ;

CREATE TABLE IF NOT EXISTS `Ser_Humano`.`roles_modulos` (
  `rol_id` INT NOT NULL,
  `modulo_id` INT NOT NULL,
  PRIMARY KEY (`rol_id`, `modulo_id`),
  INDEX `fk_roles_has_modulos_modulos1_idx` (`modulo_id` ASC),
  INDEX `fk_roles_has_modulos_roles1_idx` (`rol_id` ASC),
  CONSTRAINT `fk_roles_has_modulos_roles1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `Ser_Humano`.`roles` (`rol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roles_has_modulos_modulos1`
    FOREIGN KEY (`modulo_id`)
    REFERENCES `Ser_Humano`.`modulos` (`modulo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Ser_Humano`.`tipos_documento`
-- -----------------------------------------------------
START TRANSACTION;
USE `Ser_Humano`;
INSERT INTO `Ser_Humano`.`tipos_documento` (`tipo_doc_id`, `tipo_documento`) VALUES ('1', '1');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Ser_Humano`.`modalidad_academica`
-- -----------------------------------------------------
START TRANSACTION;
USE `Ser_Humano`;
INSERT INTO `Ser_Humano`.`modalidad_academica` (`modalidad_id`, `modalidad`) VALUES (1, 'T');
INSERT INTO `Ser_Humano`.`modalidad_academica` (`modalidad_id`, `modalidad`) VALUES (2, 'TC');
INSERT INTO `Ser_Humano`.`modalidad_academica` (`modalidad_id`, `modalidad`) VALUES (3, 'TE');
INSERT INTO `Ser_Humano`.`modalidad_academica` (`modalidad_id`, `modalidad`) VALUES (4, 'UN');
INSERT INTO `Ser_Humano`.`modalidad_academica` (`modalidad_id`, `modalidad`) VALUES (5, 'ES');
INSERT INTO `Ser_Humano`.`modalidad_academica` (`modalidad_id`, `modalidad`) VALUES (6, 'MG');
INSERT INTO `Ser_Humano`.`modalidad_academica` (`modalidad_id`, `modalidad`) VALUES (7, 'DOC');

COMMIT;

